[package]
name = "nclist"
version = "0.1.0"
authors = ["Arno Velds <a.velds@nki.nl>"]
edition = "2018"

[dependencies]
itertools = "0.8.2"

[dev-dependencies]
criterion = "0.3.1"
rand = "0.7.3"

[profile.release]
debug = true

[[bench]]
name = "bench"
harness = false
