[package]
name = "nclist"
version = "0.1.0"
authors = ["Arno Velds <a.velds@nki.nl>"]

[dependencies]
itertools = "0.7.7"

[dev-dependencies]
criterion = "0.2.2"

[[bench]]
name = "bench"
harness = false
